const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Pesawat: 0},
	{TSkor: 0},
	{BG: 0},
	{Keyboard: 0},
	{TWin: 0},
	{TLose: 0},
	{Fade: 0},
	{Ledakan: 0},
	{Bullet: 0},
	{damage: 0},
	{Alien: 0},
	{Rotate: 0},
	{Meteor: 0},
	{BosAlien: 0},
	{Health: 0},
	{SoundEffect: 0},
	{DamageEffect: 0},
	{TCredits: 0},
	{TCredits2: 0},
	{Judul: 0},
	{Logo: 0},
	{YourScore: 0},
	{BStart: 0},
	{BCredits: 0},
	{BMenu: 0},
	{Score: 0},
	{BosDamage: 0},
	{BosSpawned: 0},
	{msicOn: 0}
];

self.InstanceType = {
	Pesawat: class extends self.ISpriteInstance {},
	TSkor: class extends self.ITextInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	TWin: class extends self.ITextInstance {},
	TLose: class extends self.ITextInstance {},
	Ledakan: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Alien: class extends self.ISpriteInstance {},
	Meteor: class extends self.ISpriteInstance {},
	BosAlien: class extends self.ISpriteInstance {},
	Health: class extends self.ISpriteInstance {},
	SoundEffect: class extends self.IInstance {},
	DamageEffect: class extends self.ITiledBackgroundInstance {},
	TCredits: class extends self.ITextInstance {},
	TCredits2: class extends self.ITextInstance {},
	Judul: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ITiledBackgroundInstance {},
	YourScore: class extends self.ITextInstance {},
	BStart: class extends self.IButtonInstance {},
	BCredits: class extends self.IButtonInstance {},
	BMenu: class extends self.IButtonInstance {}
}